import { describe, it, expect } from "vitest";
import { matchOccurrencesToBankLinks, type BankLinkSlim } from "../account-matcher";
import type { VirtualOccurrence } from "../types";

function makeOccurrence(overrides: Partial<VirtualOccurrence>): VirtualOccurrence {
  return {
    id: null,
    itemId: "item-default",
    source: "MANUAL",
    categoryId: "cat-default",
    categoryCode: "CAT",
    categoryName: "Cat",
    kind: "EXPENSE",
    name: "Test",
    description: null,
    scheduledDate: new Date("2026-05-05"),
    effectiveDate: null,
    amountClp: 100_000,
    amountOriginal: 100_000,
    currency: "CLP",
    ufValueUsed: null,
    status: "PROJECTED",
    installationId: null,
    installationName: null,
    bankTransactionId: null,
    isVirtual: true,
    isAutoGenerated: false,
    actualAmountClp: null,
    varianceClp: null,
    hasIpcAdjustment: false,
    ipcAdjustmentMonths: null,
    crmAccountId: null,
    dteId: null,
    nickname: null,
    modoCobro: "DIRECTO",
    ...overrides,
  };
}

describe("matchOccurrencesToBankLinks", () => {
  it("matches occurrence to link with same category and date within tolerance, computes variance", async () => {
    const occ = makeOccurrence({
      categoryId: "cat-tel",
      scheduledDate: new Date("2026-05-05"),
      amountClp: 200_000,
      itemId: "item-1",
    });
    const link: BankLinkSlim = {
      bankTransactionId: "tx-1",
      transactionDate: new Date("2026-05-07"),
      amountClp: 220_000,
      categoryId: "cat-tel",
    };
    const result = await matchOccurrencesToBankLinks([occ], [link], { matchDaysTolerance: 5 });
    expect(result.length).toBe(1);
    expect(result[0].status).toBe("PAID");
    expect(result[0].actualAmountClp).toBe(220_000);
    expect(result[0].varianceClp).toBe(20_000);
    expect(result[0].bankTransactionId).toBe("tx-1");
    expect(result[0].effectiveDate?.toISOString().slice(0, 10)).toBe("2026-05-07");
  });

  it("does NOT match when categories differ", async () => {
    const occ = makeOccurrence({ categoryId: "cat-A", scheduledDate: new Date("2026-05-05"), amountClp: 100_000, itemId: "item-1" });
    const link: BankLinkSlim = {
      bankTransactionId: "tx-1",
      transactionDate: new Date("2026-05-05"),
      amountClp: 100_000,
      categoryId: "cat-B",
    };
    const result = await matchOccurrencesToBankLinks([occ], [link], { matchDaysTolerance: 5 });
    expect(result).toEqual([]);
  });

  it("respects date tolerance window", async () => {
    const occ = makeOccurrence({ categoryId: "cat-X", scheduledDate: new Date("2026-05-05"), itemId: "item-1" });
    const link: BankLinkSlim = {
      bankTransactionId: "tx-1",
      transactionDate: new Date("2026-05-25"), // 20 days off
      amountClp: 100_000,
      categoryId: "cat-X",
    };
    const result = await matchOccurrencesToBankLinks([occ], [link], { matchDaysTolerance: 5 });
    expect(result).toEqual([]);
  });

  it("prefers occurrence with smallest date diff when multiple match", async () => {
    const occA = makeOccurrence({ itemId: "A", categoryId: "cat-X", scheduledDate: new Date("2026-05-01") });
    const occB = makeOccurrence({ itemId: "B", categoryId: "cat-X", scheduledDate: new Date("2026-05-06") });
    const link: BankLinkSlim = {
      bankTransactionId: "tx-1",
      transactionDate: new Date("2026-05-05"),
      amountClp: 100_000,
      categoryId: "cat-X",
    };
    const result = await matchOccurrencesToBankLinks([occA, occB], [link], { matchDaysTolerance: 30 });
    expect(result.length).toBe(1);
    expect(result[0].itemId).toBe("B");
  });

  it("does not double-use a single bank link across multiple matches", async () => {
    const occA = makeOccurrence({ itemId: "A", categoryId: "cat-X", scheduledDate: new Date("2026-05-05") });
    const occB = makeOccurrence({ itemId: "B", categoryId: "cat-X", scheduledDate: new Date("2026-05-05") });
    const link: BankLinkSlim = {
      bankTransactionId: "tx-1",
      transactionDate: new Date("2026-05-05"),
      amountClp: 100_000,
      categoryId: "cat-X",
    };
    const result = await matchOccurrencesToBankLinks([occA, occB], [link], { matchDaysTolerance: 5 });
    expect(result.length).toBe(1);
  });

  it("skips occurrences already matched (bankTransactionId set)", async () => {
    const occ = makeOccurrence({
      itemId: "item-1",
      categoryId: "cat-X",
      bankTransactionId: "tx-old",
    });
    const link: BankLinkSlim = {
      bankTransactionId: "tx-new",
      transactionDate: new Date("2026-05-05"),
      amountClp: 100_000,
      categoryId: "cat-X",
    };
    const result = await matchOccurrencesToBankLinks([occ], [link], { matchDaysTolerance: 5 });
    expect(result).toEqual([]);
  });

  it("skips occurrences with status != PROJECTED", async () => {
    const occ = makeOccurrence({
      itemId: "item-1",
      categoryId: "cat-X",
      status: "PAID",
    });
    const link: BankLinkSlim = {
      bankTransactionId: "tx-new",
      transactionDate: new Date("2026-05-05"),
      amountClp: 100_000,
      categoryId: "cat-X",
    };
    const result = await matchOccurrencesToBankLinks([occ], [link], { matchDaysTolerance: 5 });
    expect(result).toEqual([]);
  });

  it("skips occurrences with itemId === null (auto-generated, no DB record to update)", async () => {
    const occ = makeOccurrence({
      itemId: null,
      categoryId: "cat-X",
    });
    const link: BankLinkSlim = {
      bankTransactionId: "tx-new",
      transactionDate: new Date("2026-05-05"),
      amountClp: 100_000,
      categoryId: "cat-X",
    };
    const result = await matchOccurrencesToBankLinks([occ], [link], { matchDaysTolerance: 5 });
    expect(result).toEqual([]);
  });
});
