import { describe, it, expect } from "vitest";
import {
  consolidateIncomeOccurrences,
  filterOccurrencesWithConciliationPriority,
} from "../projection.service";
import type { VirtualOccurrence } from "../types";

/**
 * Regla nueva (punto A): cuando una factura real cae en el MISMO bucket que una
 * programación (proyección pura) del mismo cliente+instalación —típicamente
 * porque el usuario MOVIÓ la factura ahí— el flujo ya NO fusiona: conserva la
 * programación marcándola `collidesWithInvoice`. Ambas suman y el usuario borra
 * la que sobra. La marca la exime del dedup de conciliación (nunca se oculta).
 */

let seq = 0;
function occ(part: Partial<VirtualOccurrence>): VirtualOccurrence {
  return {
    id: `occ_${seq++}`,
    itemId: "item_A",
    source: "CONTRACT",
    categoryId: "cat_ventas",
    categoryCode: "ING_CONTRATO",
    categoryName: "Ventas por contrato",
    kind: "INCOME",
    name: "Contrato",
    description: null,
    notes: null,
    scheduledDate: new Date("2026-06-18T00:00:00Z"),
    effectiveDate: null,
    amountClp: 0,
    amountOriginal: 0,
    currency: "CLP",
    ufValueUsed: null,
    status: "PROJECTED",
    installationId: "inst_1",
    installationName: "Instalación 1",
    crmAccountId: "crm_1",
    crmAccountName: "Cliente Uno",
    bankTransactionId: null,
    isVirtual: true,
    isAutoGenerated: true,
    actualAmountClp: null,
    varianceClp: null,
    hasIpcAdjustment: false,
    ipcAdjustmentMonths: null,
    dteId: null,
    nickname: null,
    modoCobro: "DIRECTO",
    ...part,
  };
}

describe("collidesWithInvoice — consolidateIncomeOccurrences", () => {
  it("factura y programación en el MISMO bucket → conserva ambas y marca la programación", () => {
    // Programación día 18 (proyección pura) + factura movida al 19 (misma semana ISO).
    const projection = occ({
      dteId: null,
      amountClp: 5000,
      scheduledDate: new Date("2026-06-18T00:00:00Z"),
    });
    const invoice = occ({
      dteId: "dte_1",
      amountClp: 0, // sombra $0 → se resuelve al bruto real
      scheduledDate: new Date("2026-06-19T00:00:00Z"),
    });

    const out = consolidateIncomeOccurrences(
      [projection, invoice],
      new Map([["dte_1", 8000]]),
      "weekly",
    );

    // Ambas sobreviven (antes la programación se descartaba).
    expect(out).toHaveLength(2);
    const proj = out.find((o) => o.dteId === null);
    const inv = out.find((o) => o.dteId === "dte_1");
    expect(proj?.collidesWithInvoice).toBe(true);
    expect(inv).toBeTruthy();
    // Suman las dos: 5000 (programación) + 8000 (bruto factura).
    const total = out.reduce((s, o) => s + (o.dteId ? 8000 : o.amountClp), 0);
    expect(total).toBe(13000);
  });

  it("factura en OTRA semana → la programación NO se marca (no se topan)", () => {
    const projection = occ({
      dteId: null,
      amountClp: 5000,
      scheduledDate: new Date("2026-06-18T00:00:00Z"),
    });
    const invoice = occ({
      dteId: "dte_1",
      amountClp: 8000,
      scheduledDate: new Date("2026-06-26T00:00:00Z"), // semana distinta
    });

    const out = consolidateIncomeOccurrences(
      [projection, invoice],
      new Map([["dte_1", 8000]]),
      "weekly",
    );
    const proj = out.find((o) => o.dteId === null);
    expect(proj?.collidesWithInvoice).toBeFalsy();
  });

  it("distinta instalación mismo bucket → no se topan (no marca)", () => {
    const projection = occ({
      dteId: null,
      amountClp: 5000,
      installationId: "inst_1",
    });
    const invoice = occ({
      dteId: "dte_1",
      amountClp: 8000,
      installationId: "inst_2",
    });
    const out = consolidateIncomeOccurrences(
      [projection, invoice],
      new Map([["dte_1", 8000]]),
      "weekly",
    );
    expect(out.find((o) => o.dteId === null)?.collidesWithInvoice).toBeFalsy();
  });
});

describe("collidesWithInvoice — exención en filterOccurrencesWithConciliationPriority", () => {
  it("la programación marcada NUNCA se oculta, aunque haya una factura conciliada en la celda", () => {
    const reconciled = occ({
      dteId: "dte_1",
      bankTransactionId: "bt_1",
      amountClp: 8000,
      actualAmountClp: 8000,
      status: "PAID",
    });
    const marked = occ({
      dteId: null,
      amountClp: 5000,
      collidesWithInvoice: true,
    });
    const visible = filterOccurrencesWithConciliationPriority([
      reconciled,
      marked,
    ]);
    expect(visible).toContain(marked); // exenta: sobrevive
    expect(visible).toContain(reconciled);
  });

  it("no-regresión: sin la marca, la proyección-sombra SÍ se oculta ante la conciliada", () => {
    const reconciled = occ({
      dteId: "dte_1",
      bankTransactionId: "bt_1",
      amountClp: 8000,
      status: "PAID",
    });
    const shadow = occ({ dteId: null, amountClp: 5000 }); // sin flag
    const visible = filterOccurrencesWithConciliationPriority([
      reconciled,
      shadow,
    ]);
    expect(visible).not.toContain(shadow);
  });
});
