import { describe, it, expect } from "vitest";
import { filterOccurrencesWithConciliationPriority } from "../projection.service";
import type { VirtualOccurrence } from "../types";

let seq = 0;
function occ(part: Partial<VirtualOccurrence>): VirtualOccurrence {
  return {
    id: `occ_${seq++}`,
    itemId: null,
    source: "MANUAL",
    categoryId: "cat_ventas",
    categoryCode: "ING_CONTRATO",
    categoryName: "Ventas por contrato",
    kind: "INCOME",
    name: "Factura",
    description: null,
    notes: null,
    scheduledDate: new Date("2026-06-03T00:00:00Z"),
    effectiveDate: null,
    amountClp: 1000,
    amountOriginal: 1000,
    currency: "CLP",
    ufValueUsed: null,
    status: "PROJECTED",
    installationId: null,
    installationName: null,
    crmAccountId: null,
    crmAccountName: null,
    bankTransactionId: null,
    isVirtual: true,
    isAutoGenerated: true,
    actualAmountClp: null,
    varianceClp: null,
    hasIpcAdjustment: false,
    ipcAdjustmentMonths: null,
    dteId: null,
    nickname: null,
    modoCobro: "DIRECTO",
    ...part,
  };
}

describe("filterOccurrencesWithConciliationPriority — scope de INGRESOS", () => {
  it("una factura cobrada NO oculta las facturas impagas de OTROS clientes (misma categoría/semana)", () => {
    // Regresión del bug "no salen todas las facturas de DTE emitidos": antes
    // cualquier conciliación en la celda categoría+semana borraba todas las
    // proyectadas del resto de clientes (y del subtotal).
    const paidA = occ({
      dteId: "dte_a",
      crmAccountId: "crm_A",
      bankTransactionId: "tx_1",
      status: "PAID",
      actualAmountClp: 1000,
    });
    const unpaidB = occ({ dteId: "dte_b", crmAccountId: "crm_B" });
    const unpaidC = occ({ dteId: "dte_c", crmAccountId: "crm_C" });

    const visible = filterOccurrencesWithConciliationPriority([paidA, unpaidB, unpaidC]);
    expect(visible).toContain(paidA);
    expect(visible).toContain(unpaidB);
    expect(visible).toContain(unpaidC);
    expect(visible).toHaveLength(3);
  });

  it("la conciliación SÍ reemplaza la proyección-sombra del MISMO movimiento (item)", () => {
    const paid = occ({ itemId: "item_X", bankTransactionId: "tx_1", status: "PAID", dteId: "dte_x" });
    const shadow = occ({ itemId: "item_X", dteId: null }); // sombra del mismo item
    const otherClient = occ({ itemId: "item_Y", crmAccountId: "crm_Y" });

    const visible = filterOccurrencesWithConciliationPriority([paid, shadow, otherClient]);
    expect(visible).toContain(paid);
    expect(visible).not.toContain(shadow); // shadow del mismo item se descarta
    expect(visible).toContain(otherClient); // otro cliente sobrevive
  });

  it("una factura real impaga NO se oculta aunque un hermano del mismo item esté conciliado", () => {
    // Una factura extra (dteId) de la misma cuenta/semana es un documento
    // distinto: debe verse aunque el cobro del contrato ya esté conciliado.
    const paidContract = occ({
      itemId: "item_X",
      dteId: "dte_pagada",
      bankTransactionId: "tx_1",
      status: "PAID",
    });
    const extraInvoice = occ({ itemId: "item_X", dteId: "dte_extra" }); // impaga, mismo item
    const visible = filterOccurrencesWithConciliationPriority([paidContract, extraInvoice]);
    expect(visible).toContain(paidContract);
    expect(visible).toContain(extraInvoice);
  });

  it("la conciliación reemplaza la proyección de la MISMA cuenta+instalación (sin item)", () => {
    const paid = occ({
      crmAccountId: "crm_A",
      installationId: "inst_1",
      bankTransactionId: "tx_1",
      status: "PAID",
    });
    const projSameAcct = occ({ crmAccountId: "crm_A", installationId: "inst_1", dteId: null });
    const projOtherAcct = occ({ crmAccountId: "crm_B", installationId: "inst_2", dteId: null });

    const visible = filterOccurrencesWithConciliationPriority([paid, projSameAcct, projOtherAcct]);
    expect(visible).toContain(paid);
    expect(visible).not.toContain(projSameAcct);
    expect(visible).toContain(projOtherAcct);
  });

  it("EGRESOS: mantiene la regla amplia (conciliación de la celda reemplaza toda proyección)", () => {
    const paidExpense = occ({
      kind: "EXPENSE",
      categoryCode: "EGR_OTRO",
      bankTransactionId: "tx_1",
      status: "PAID",
    });
    const projExpense1 = occ({ kind: "EXPENSE", categoryCode: "EGR_OTRO", itemId: "gasto_1" });
    const projExpense2 = occ({ kind: "EXPENSE", categoryCode: "EGR_OTRO", itemId: "gasto_2" });

    const visible = filterOccurrencesWithConciliationPriority([
      paidExpense,
      projExpense1,
      projExpense2,
    ]);
    expect(visible).toEqual([paidExpense]);
  });

  it("sin conciliación → no filtra nada", () => {
    const a = occ({ dteId: "dte_a", crmAccountId: "crm_A" });
    const b = occ({ dteId: "dte_b", crmAccountId: "crm_B" });
    const visible = filterOccurrencesWithConciliationPriority([a, b]);
    expect(visible).toHaveLength(2);
  });
});
