import { describe, it, expect } from "vitest";
import { markExtraInvoices } from "../projection.service";
import { utcCalendarDay } from "../recurrence-engine";
import type { VirtualOccurrence } from "../types";

const day = (iso: string) => utcCalendarDay(new Date(iso));

const BUCKETS = [
  { key: "W1", start: day("2026-06-01"), end: day("2026-06-07") },
  { key: "W2", start: day("2026-06-08"), end: day("2026-06-14") },
];

let seq = 0;
function occ(part: Partial<VirtualOccurrence>): VirtualOccurrence {
  return {
    id: `occ_${seq++}`,
    itemId: "item_A",
    source: "CONTRACT",
    categoryId: "cat_ventas",
    categoryCode: "ING_CONTRATO",
    categoryName: "Ventas por contrato",
    kind: "INCOME",
    name: "Contrato",
    description: null,
    notes: null,
    scheduledDate: new Date("2026-06-03T00:00:00Z"),
    effectiveDate: null,
    amountClp: 0,
    amountOriginal: 0,
    currency: "CLP",
    ufValueUsed: null,
    status: "PROJECTED",
    installationId: "inst_1",
    installationName: "Instalación 1",
    crmAccountId: "crm_1",
    crmAccountName: "Cliente Uno",
    bankTransactionId: null,
    isVirtual: true,
    isAutoGenerated: true,
    actualAmountClp: null,
    varianceClp: null,
    hasIpcAdjustment: false,
    ipcAdjustmentMonths: null,
    dteId: null,
    nickname: null,
    modoCobro: "DIRECTO",
    ...part,
  };
}

/** Réplica de la clave de sub-fila de buildRows para INCOME (sin conc/periodic). */
function subRowKey(o: VirtualOccurrence): string {
  return o.isExtraInvoice && o.dteId
    ? `_extra:${o.dteId}`
    : (o.itemId ?? (o.dteId ? `_dte:${o.dteId}` : "_orphan"));
}

function bucketTotalsByKey(occs: VirtualOccurrence[]): Record<string, number> {
  const totals: Record<string, number> = {};
  for (const o of occs) {
    const d = utcCalendarDay(o.effectiveDate ?? o.scheduledDate);
    const b = BUCKETS.find((bk) => d >= bk.start && d <= bk.end);
    if (!b) continue;
    totals[b.key] = (totals[b.key] ?? 0) + o.amountClp;
  }
  return totals;
}

describe("markExtraInvoices", () => {
  it("INVARIANTE: el subtotal INCOME por bucket es idéntico antes/después", () => {
    const occs = [
      occ({ dteId: "dte_1", amountClp: 1000, scheduledDate: new Date("2026-06-03T00:00:00Z") }),
      occ({ dteId: "dte_2", amountClp: 400, scheduledDate: new Date("2026-06-04T00:00:00Z") }),
    ];
    const before = bucketTotalsByKey(occs);

    markExtraInvoices(occs, BUCKETS, new Map([["dte_1", 1], ["dte_2", 2]]));
    const after = bucketTotalsByKey(occs);

    // El flag NO cambia montos → subtotal idéntico.
    expect(after).toEqual(before);
    expect(after).toEqual({ W1: 1400 });

    // Pero AHORA hay 2 sub-filas distintas (el split ocurrió).
    const keys = new Set(occs.map(subRowKey));
    expect(keys.size).toBe(2);
    expect([...keys].some((k) => k.startsWith("_extra:"))).toBe(true);
  });

  it("2 DTEs mismo item/bucket → 1 contrato (folio menor) + 1 _extra marcado", () => {
    const first = occ({ dteId: "dte_lo", scheduledDate: new Date("2026-06-03T00:00:00Z") });
    const second = occ({ dteId: "dte_hi", scheduledDate: new Date("2026-06-03T00:00:00Z") });
    const occs = [second, first]; // orden de llegada invertido a propósito

    markExtraInvoices(occs, BUCKETS, new Map([["dte_lo", 10], ["dte_hi", 20]]));

    expect(first.isExtraInvoice).toBeFalsy();
    expect(second.isExtraInvoice).toBe(true);
    expect(subRowKey(second)).toBe("_extra:dte_hi");
  });

  it("la extra conserva crmAccountId/installationId (buildRows hereda el cliente)", () => {
    const first = occ({ dteId: "dte_1" });
    const second = occ({ dteId: "dte_2" });
    markExtraInvoices([first, second], BUCKETS, new Map([["dte_1", 1], ["dte_2", 2]]));
    expect(second.isExtraInvoice).toBe(true);
    expect(second.crmAccountId).toBe("crm_1");
    expect(second.installationId).toBe("inst_1");
  });

  it("1 solo DTE en el bucket → sin _extra (no-regresión)", () => {
    const only = occ({ dteId: "dte_1" });
    markExtraInvoices([only], BUCKETS, new Map([["dte_1", 1]]));
    expect(only.isExtraInvoice).toBeFalsy();
  });

  it("3 DTEs en el mismo bucket → 1 contrato + 2 _extra", () => {
    const occs = [
      occ({ dteId: "dte_1", scheduledDate: new Date("2026-06-02T00:00:00Z") }),
      occ({ dteId: "dte_2", scheduledDate: new Date("2026-06-03T00:00:00Z") }),
      occ({ dteId: "dte_3", scheduledDate: new Date("2026-06-04T00:00:00Z") }),
    ];
    markExtraInvoices(occs, BUCKETS, new Map());
    expect(occs.filter((o) => o.isExtraInvoice).length).toBe(2);
    expect(occs.find((o) => o.dteId === "dte_1")?.isExtraInvoice).toBeFalsy();
  });

  it("determinismo: mismo input, mismo 'primero' sin importar orden de llegada", () => {
    const run = (order: string[]) => {
      const occs = order.map((id) =>
        occ({ dteId: id, scheduledDate: new Date("2026-06-03T00:00:00Z") }),
      );
      markExtraInvoices(occs, BUCKETS, new Map([["dte_a", 5], ["dte_b", 5], ["dte_c", 5]]));
      return occs.find((o) => !o.isExtraInvoice)?.dteId;
    };
    // Folios iguales → desempate por dteId asc → "dte_a" siempre primero.
    expect(run(["dte_c", "dte_a", "dte_b"])).toBe("dte_a");
    expect(run(["dte_b", "dte_c", "dte_a"])).toBe("dte_a");
  });

  it("DTEs del mismo item en buckets distintos → sin _extra (no colisionan)", () => {
    const w1 = occ({ dteId: "dte_1", scheduledDate: new Date("2026-06-03T00:00:00Z") });
    const w2 = occ({ dteId: "dte_2", scheduledDate: new Date("2026-06-10T00:00:00Z") });
    markExtraInvoices([w1, w2], BUCKETS, new Map());
    expect(w1.isExtraInvoice).toBeFalsy();
    expect(w2.isExtraInvoice).toBeFalsy();
  });

  it("DTEs de items distintos en el mismo bucket → sin _extra", () => {
    const a = occ({ dteId: "dte_1", itemId: "item_A" });
    const b = occ({ dteId: "dte_2", itemId: "item_B" });
    markExtraInvoices([a, b], BUCKETS, new Map());
    expect(a.isExtraInvoice).toBeFalsy();
    expect(b.isExtraInvoice).toBeFalsy();
  });
});
