
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local file (ignored on Vercel where env vars come from the platform).
config({ path: ".env.local" });

// Build-time placeholder: `prisma generate` does not connect to the DB; it only
// needs a valid-looking URL so the config parses. At runtime, `@prisma/client`
// reads env("DATABASE_URL") from schema.prisma and will fail explicitly if the
// real value is missing — so tolerating a placeholder here is safe.
// Main use case: Vercel Preview deployments where DATABASE_URL might not be
// configured for non-production environments.
const PLACEHOLDER_URL = "postgresql://build:build@127.0.0.1:5432/build";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL || PLACEHOLDER_URL,
    directUrl:
      process.env.DIRECT_DATABASE_URL ||
      process.env.DATABASE_URL ||
      PLACEHOLDER_URL,
  },
});
