import type {
  FinanceCashflowItem,
  FinanceCashflowCategory,
  FinanceCashflowItemKind,
  FinanceCashflowItemSource,
  FinanceCashflowOccurrenceStatus,
  FinanceCashflowConfig,
} from "@prisma/client";

export type {
  FinanceCashflowItem,
  FinanceCashflowCategory,
  FinanceCashflowItemKind,
  FinanceCashflowItemSource,
  FinanceCashflowOccurrenceStatus,
  FinanceCashflowConfig,
};

export interface VirtualOccurrence {
  id: string | null;
  itemId: string | null;
  source: FinanceCashflowItemSource;
  categoryId: string | null;
  categoryCode: string;
  categoryName: string;
  kind: FinanceCashflowItemKind;
  name: string;
  description: string | null;
  scheduledDate: Date;
  effectiveDate: Date | null;
  amountClp: number;
  amountOriginal: number;
  currency: string;
  ufValueUsed: number | null;
  status: FinanceCashflowOccurrenceStatus;
  installationId: string | null;
  installationName: string | null;
  bankTransactionId: string | null;
  isVirtual: boolean;
  isAutoGenerated: boolean;
}

export interface ProjectionRange {
  from: Date;
  to: Date;
  granularity: "weekly" | "monthly";
}

export interface ProjectionBucket {
  key: string;
  label: string;
  start: Date;
  end: Date;
  income: number;
  expense: number;
  net: number;
  occurrences: VirtualOccurrence[];
}

export interface ProjectionRow {
  categoryId: string | null;
  categoryCode: string;
  categoryName: string;
  kind: FinanceCashflowItemKind;
  values: { bucketKey: string; amount: number }[];
  total: number;
}

export interface ProjectionMatrix {
  range: ProjectionRange;
  buckets: ProjectionBucket[];
  rows: ProjectionRow[];
  totals: {
    totalIncome: number;
    totalExpense: number;
    totalNet: number;
  };
  openingBalanceClp: number;
  cumulativeBalances: { bucketKey: string; balanceClp: number }[];
}
