import type {
  FinanceCashflowItem,
  FinanceCashflowCategory,
  FinanceCashflowItemKind,
  FinanceCashflowItemSource,
  FinanceCashflowOccurrenceStatus,
  FinanceCashflowConfig,
} from "@prisma/client";

export type {
  FinanceCashflowItem,
  FinanceCashflowCategory,
  FinanceCashflowItemKind,
  FinanceCashflowItemSource,
  FinanceCashflowOccurrenceStatus,
  FinanceCashflowConfig,
};

export interface VirtualOccurrence {
  id: string | null;
  itemId: string | null;
  source: FinanceCashflowItemSource;
  categoryId: string | null;
  categoryCode: string;
  categoryName: string;
  kind: FinanceCashflowItemKind;
  name: string;
  description: string | null;
  scheduledDate: Date;
  effectiveDate: Date | null;
  amountClp: number;
  amountOriginal: number;
  currency: string;
  ufValueUsed: number | null;
  status: FinanceCashflowOccurrenceStatus;
  installationId: string | null;
  installationName: string | null;
  /** Cuenta CRM dueña del ítem (para links a contratos / cotización origen). */
  crmAccountId: string | null;
  bankTransactionId: string | null;
  isVirtual: boolean;
  isAutoGenerated: boolean;
  /** Monto realmente ejecutado en banco (cuando hay match con un bank tx). null = aún no conciliado. */
  actualAmountClp: number | null;
  /** Diferencia real − proyectado. Positivo = gasté más / cobré más de lo proyectado. null si no hay actual. */
  varianceClp: number | null;
}

export interface ProjectionRange {
  from: Date;
  to: Date;
  granularity: "weekly" | "monthly";
}

export interface ProjectionBucket {
  key: string;
  label: string;
  start: Date;
  end: Date;
  income: number;
  expense: number;
  net: number;
  /** Suma de actualAmountClp para occurrences PAID dentro del bucket (solo INCOME). */
  actualIncome: number;
  /** Suma de actualAmountClp para occurrences PAID dentro del bucket (solo EXPENSE). */
  actualExpense: number;
  /** real − proyectado para todo el bucket: (actualIncome − income) − (actualExpense − expense). */
  varianceClp: number;
  /** Suma de créditos (amount > 0) de FinanceBankTransaction visibles en el bucket. */
  actualBankIncome: number;
  /** Suma de débitos (amount < 0) en valor absoluto. */
  actualBankExpense: number;
  /** Net real de cartola = actualBankIncome − actualBankExpense. */
  actualBankNet: number;
  /** Diferencia entre lo que el banco ejecutó y lo proyectado:
   *  (actualBankIncome − income) − (actualBankExpense − expense). */
  bankVarianceClp: number;
  occurrences: VirtualOccurrence[];
}

export interface ProjectionRowItemValue {
  bucketKey: string;
  amount: number;
  /** Suma de actualAmountClp en este bucket (null si no hay conciliación). */
  actualAmount: number | null;
  /** id de una occurrence representativa (no PAID, materializada) para DnD/popover. */
  occurrenceId: string | null;
  /** scheduledDate (yyyy-MM-dd) de una cuota representativa del bucket. Permite
   *  materializar al primer move/amount aunque occurrenceId sea null. */
  scheduledDate: string;
}

export interface ProjectionRowItemDetail {
  itemId: string;
  itemName: string;
  installationId: string | null;
  installationName: string | null;
  /** Cuenta CRM dueña del ítem — habilita link al tab Contratos. */
  crmAccountId: string | null;
  /** Nombre del cliente (CrmAccount.name) para mostrar agrupación en UI. */
  crmAccountName: string | null;
  /** Monto base del item en su moneda original (UF o CLP), tal como se
   *  guardó. Se muestra al lado del nombre para que el usuario vea el
   *  "precio del contrato" sin tener que calcularlo desde los buckets. */
  baseAmount: number;
  /** Moneda del item ("CLP" | "UF"). Útil para mostrar badge al lado del nombre. */
  currency: string;
  source: FinanceCashflowItemSource;
  /** Código del contrato CpqQuote o ref similar para mostrar en badge. */
  sourceRefCode: string | null;
  values: ProjectionRowItemValue[];
  total: number;
  totalActual: number;
}

export interface ProjectionRow {
  categoryId: string | null;
  categoryCode: string;
  categoryName: string;
  kind: FinanceCashflowItemKind;
  values: { bucketKey: string; amount: number }[];
  total: number;
  /** Sub-filas por item (instalación / contrato / template / etc) para expansión. */
  items: ProjectionRowItemDetail[];
}

export interface ProjectionMatrix {
  range: ProjectionRange;
  buckets: ProjectionBucket[];
  rows: ProjectionRow[];
  totals: {
    totalIncome: number;
    totalExpense: number;
    totalNet: number;
    totalActualIncome: number;
    totalActualExpense: number;
    totalVariance: number;
  };
  openingBalanceClp: number;
  cumulativeBalances: { bucketKey: string; balanceClp: number }[];
}
